### ISSUE TITLE
网站目录乱码

### ISSUE THREAD

**Issue by littlemoji** [adoyle-h/my-development-tools#6]
<img width="1035" alt="image" src="https://user-images.githubusercontent.com/55924059/174936974-4f75a29d-57b3-460f-b8e2-d53ae56d46a0.png">

**Comment by adoyle-h** [comment]
嗯，原因是 Github Page 用的 Jekyll 主题不支持 Github Markdown 的折叠语法。暂时找不到简单好用的页面生成工具。那我就把折叠取消了。现在网页端可以正常看了。
